# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ea78d33a3315f307f664e54162e3e977e828b572558e5be9ec54db6d22bc9a67e3954fc5b6b68805b818205c902db2c7d06ed06ca39ccb8d44337b6231045ad

test:
  secret_key_base: 9cad683af4c4040fd5255ec68a03430fdad79bf94c4f6cede774d4faa968390a2a8bec25f73861534f83a94953fd9c945cac4315b0bf330bfc068a5fe5241899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
